# Generated by Django 6.0.4 on 2026-04-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comic",
            name="category",
        ),
        migrations.RemoveField(
            model_name="video",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="permission_level",
            field=models.CharField(
                choices=[("regular", "普通权限"), ("special", "特殊权限")],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="categories",
            field=models.ManyToManyField(related_name="comics", to="api.category"),
        ),
        migrations.AddField(
            model_name="video",
            name="categories",
            field=models.ManyToManyField(related_name="videos", to="api.category"),
        ),
    ]
