# Generated by Django 6.0.4 on 2026-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_cloudfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="comics/covers/"),
        ),
    ]
