# Generated by Django 6.0.4 on 2026-04-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_comic_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comicchapter",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
