# Generated by Django 5.2.16 on 2026-07-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_comicchapter_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("resource_id", models.CharField(blank=True, max_length=36, null=True)),
                ("image_file", models.ImageField(upload_to="images/")),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("resource_type", models.CharField(choices=[("image", "单张图片"), ("album_cover", "图集封面")], default="image", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("resource_id", models.CharField(blank=True, max_length=36, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cover_image", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="album_cover", to="api.image")),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="albums", to="api.category"),
        ),
        migrations.AddField(
            model_name="album",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="albums", to="api.image"),
        ),
        migrations.AddField(
            model_name="album",
            name="uploader",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="uploaded_albums", to="auth.user"),
        ),
        migrations.AddField(
            model_name="image",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="images", to="api.category"),
        ),
        migrations.AddField(
            model_name="image",
            name="uploader",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="uploaded_images", to="auth.user"),
        ),
        migrations.AddField(
            model_name="comic",
            name="resource_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="resource_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="m3u8_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="video_type",
            field=models.CharField(choices=[("video", "视频"), ("special", "特辑")], default="video", max_length=20),
        ),
        migrations.AddField(
            model_name="video",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]