# Generated by Django 5.2.16 on 2026-07-26 04:50

from django.db import migrations
import uuid


def populate_resource_ids(apps, schema_editor):
    Comic = apps.get_model('api', 'Comic')
    Video = apps.get_model('api', 'Video')
    
    for comic in Comic.objects.filter(resource_id__isnull=True):
        comic.resource_id = str(uuid.uuid4())
        comic.save()
    
    for video in Video.objects.filter(resource_id__isnull=True):
        video.resource_id = str(uuid.uuid4())
        video.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_image_album_models'),
    ]

    operations = [
        migrations.RunPython(populate_resource_ids),
    ]