# Generated by Django 5.2.16 on 2026-07-26 05:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comic_slug_alter_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=api.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='resource_type',
            field=models.CharField(choices=[('image', '单张图片'), ('album_image', '图集图片'), ('album_cover', '图集封面')], default='image', max_length=20),
        ),
    ]
